[package]
name = "seg"
description = "segment-structured in-memory storage with eager expiration"
authors = ["Brian Martin <bmartin@twitter.com>"]

version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false

[features]

# enables setting/checking magic strings
magic = []

# metafeatures
debug = ["magic"]

# default set of enabled features
default = []

[dependencies]
ahash.workspace = true
common = { path = "../../common" }
datapool = { path = "../datapool" }
logger = { path = "../../logger" }
memmap2.workspace = true
rand = { workspace = true , features = ["small_rng", "getrandom"] }
rand_chacha.workspace = true
rand_xoshiro.workspace = true
rustcommon-metrics.workspace = true
storage-types = { path = "../types" }
thiserror.workspace = true

[dev-dependencies]
criterion = "0.3.4"
