[package]
name = "cdb_ffi"
version = "0.2.0"
authors = ["Jonathan Simms <jsimms@twitter.com>"]

[dependencies]
ccommon_rs = { path = "../../../../deps/ccommon/rust/ccommon_rs" }
cc_binding = { path = "../../../../deps/ccommon/rust/cc_binding" }

cdb_rs = { path = "../cdb_rs" }

log = "~0.4"
env_logger = "~0.5.10"
libc = "~0.2.42"
bytes = "~0.4"

[lib]
name = "cdb_ffi"
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
bindgen = "0.37.0"
