[package]
name = "waker"
authors = ["Brian Martin <bmartin@twitter.com>"]

version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
mio = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
libc = { workspace = true }
