[package]
name = "seg"
version = "0.1.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "segment-structured in-memory storage with eager expiration"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false

[features]

# enables setting/checking magic strings
magic = []

# metafeatures
debug = ["magic"]

# default set of enabled features
default = []

[dependencies]
ahash = "0.7.2"
common = { path = "../../common" }
logger = { path = "../../logger" }
memmap2 = "0.2.2"
metrics = { path = "../../metrics" }
rand = { version = "0.8.3", features = ["small_rng", "getrandom"] }
rand_chacha = { version = "0.3.0" }
rand_xoshiro = { version = "0.6.0" }
thiserror = "1.0.24"

[dev-dependencies]
criterion = "0.3.4"
