[package]
name = "protocol-memcache"
version = "0.0.1"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "protocols used in Pelikan servers"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[[bench]]
name = "memcache"
path = "benches/memcache.rs"
harness = false

[dependencies]
common = { path = "../../common" }
config = { path = "../../config" }
logger = { path = "../../logger" }
metrics = { path = "../../metrics" }
protocol-common = { path = "../../protocol/common" }
session = { path = "../../session" }
storage-types = { path = "../../storage/types" }

[dev-dependencies]
criterion = "0.3.4"

[features]
default = ["stats"]
stats = []