# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pelikan Cache
email: pelikan-cache@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Pelikan is a framework for building cache services.
baseurl: "/pelikan"
url: "https://twitter.github.io"
githuburl: "https://github.com/twitter/pelikan"
discussurl: "https://pelikan.zulipchat.com"
twitter_username: pelikan_cache
github_username: twitter
favicon: "/pelikan/asset/img/round_icon.jpg"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

# permalink: /:year/:month/:day/:title.html
permalink: /:year/:title.html

# Other collection
collections:
  talks:
    output: true
    permalink: /talks/:path/
