[workspace]
members = [
    "src/rust/common",
    "src/rust/config",
    "src/rust/core/server",
    "src/rust/entrystore",
    "src/rust/logger",
    "src/rust/metrics",
    "src/rust/macros",
    "src/rust/protocol",
    "src/rust/proxy/momento",
    "src/rust/queues",
    "src/rust/server/pingserver",
    "src/rust/server/segcache",
    "src/rust/session",
    "src/rust/storage/seg",
    "src/rust/storage/types",
]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.dev]
debug = true
opt-level = 0
