[package]
name = "entrystore"
version = "0.0.1"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "a collection of entry storage types for use in Pelikan servers"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[dependencies]
config = { path = "../config" }
protocol = { path = "../protocol" }
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }
seg = { path = "../storage/seg" }