[package]
name = "common"
version = "0.1.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "common types, traits, and helper functions for Pelikan servers"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boring = "2.0.0"
config = { path = "../config" }
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }