[package]
name = "macros"
version = "0.1.0"
authors = ["Sean Lynch <seanl@twitter.com>"]
edition = "2018"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = "1.0.0"
proc-macro2 = "1.0.0"