[package]
name = "ccommon-derive"
version = "0.1.0"
authors = ["Sean Lynch <slynch@twitter.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.0", features = [ "parsing" ] }
quote = "1.0.0"
proc-macro2 = "1.0.0"
proc-macro-crate = "0.1.4"
import-link-flags = { path="../import-link-flags" }
