[package]
name = "pingserver"
version = "0.1.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"

[lib]
name = "pelikan_pingserver_rs"
path = "src/lib.rs"
doc = true

[[bin]]
name = "pelikan_pingserver_rs"
path = "src/main.rs"
doc = false

[[test]]
name = "integration"
path = "tests/integration.rs"
harness = false

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false

[features]
# debug = ["segcache/debug"]

[dependencies]
backtrace = "0.3.56"
config = { path = "../../config" }
entrystore = { path = "../../entrystore" }
protocol = { path = "../../protocol" }
rustcommon-logger = { git = "https://github.com/twitter/rustcommon" }
rustcommon-fastmetrics = { git = "https://github.com/twitter/rustcommon" }
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }
server = { path = "../../core/server" }

[dev-dependencies]
criterion = "0.3"
