[package]
name = "pingserver"
version = "0.1.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "a simple ascii ping/pong server"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[lib]
name = "pelikan_pingserver_rs"
path = "src/lib.rs"
doc = true

[[bin]]
name = "pelikan_pingserver_rs"
path = "src/main.rs"
doc = false

[[test]]
name = "integration"
path = "tests/integration.rs"
harness = false

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false

[features]

[dependencies]
backtrace = "0.3.56"
clap = "2.33.3"
config = { path = "../../config" }
entrystore = { path = "../../entrystore" }
logger = { path = "../../logger" }
metrics = { path = "../../metrics" }
protocol-ping = { path = "../../protocol/ping", features = ["server"] }
server = { path = "../../core/server" }

[dev-dependencies]
criterion = "0.3"
