[package]
name = "pelikan_twemcache_http"
version = "0.1.0"
authors = ["Sean Lynch <slynch@twitter.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.5.1"
bytes = "0.5.2"
clap = "2.33"
log = "0.4.8"
thiserror = "1.0.8"
tokio = { version = "0.2.2", features = [ "net" ] }

rustcore = { path = "../../rustcore" }

httparse = "1.3.4"
httpdate = "0.3.2"
httpencode = { path = "../../rust-util/httpencode" }

[dependencies.ccommon]
path = "../../../deps/ccommon/rust/ccommon_rs"
package = "ccommon_rs"

[dependencies.ccommon_sys]
path = "../../../deps/ccommon/rust/cc_binding"
package = "cc_binding"

[dependencies.pelikan]
path = "../../rust-util/pelikan"
features = [ "protocol_memcache", "protocol_admin", "slab", "hotkey" ]

[dependencies.pelikan-sys]
path = "../../rust-util/pelikan-sys"

[build-dependencies]
cc = "1.0.48"
bindgen = "0.52"
