[package]
name = "ccommon_rs"
version = "0.1.0"
authors = ["Jonathan Simms <jsimms@twitter.com>", "Sean Lynch <slynch@twitter.com>"]
edition = "2018"

[features]
derive = [ "ccommon-derive" ]

default = [ "derive" ]

[lib]
name = "ccommon_rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
cc_binding = { path = "../cc_binding" }
libc = "0.2.0"
log = "0.4.0"

[dependencies.ccommon-derive]
path = "../ccommon-derive"
optional = true

[build-dependencies]
autocfg = "0.1.7"

[dev-dependencies]
rusty-fork = "0.2.0"
gag = "0.1.10"
