[package]
name = "pelikan_pingserver_rs"
authors = ["Sean Lynch <slynch@twitter.com>"]
edition = "2018"
version = "0.0.0"

[dependencies]
clap = "2.33"
lazy_static = "1.4"
log = "0.4.8"
libc = "0.2"

pelikan = { path="../../rust-util/pelikan", features=["protocol_admin", "protocol_ping"] }
rustcore = { path="../../rustcore" }

[dependencies.pelikan-sys]
path = "../../rust-util/pelikan-sys"
features = [ "protocol_ping", "protocol_admin" ]

[dependencies.ccommon]
path = "../../../deps/ccommon/rust/ccommon_rs"
package = "ccommon_rs"

[dependencies.ccommon-sys]
path = "../../../deps/ccommon/rust/cc_binding"
package = "cc_binding"
