[package]
name = "pingserver-rs"
version = "0.0.1"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "an over-engineered ping server written in Rust"
license = "Apache-2.0"

[dependencies]
bytes = "0.4.12"
chrono = "0.4.11"
config = { path = "../../rust/config" }
log = { version = "0.4.8", features = ["std"] }
mio = "0.6.21"
slab = "0.4.2"
