[package]
name = "server"
version = "0.1.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "core server event loops and threads for Pelikan servers"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.6.2"
backtrace = "0.3.56"
bytes = "1.0.1"
common = { path = "../../common" }
config = { path = "../../config" }
crossbeam-channel = "0.5.0"
libc = "0.2.83"
logger = { path = "../../logger" }
metrics = { path = "../../metrics" }
mio = { version = "0.7.7", features = ["os-poll", "tcp"] }
protocol = { path = "../../protocol" }
queues = { path = "../../queues" }
rand = "0.8.0"
rtrb = "0.1.3"
rustcommon-logger = { git = "https://github.com/twitter/rustcommon" }
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
session = { path = "../../session" }
entrystore = { path = "../../entrystore" }
slab = "0.4.2"
strum = "0.20.0"
strum_macros = "0.20.1"
sysconf = "0.3.4"
thiserror = "1.0.23"

[dev-dependencies]
criterion = "0.3"

