[package]
name = "metrics"
version = "0.1.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "metrics for Pelikan servers"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustcommon-metrics = { git = "https://github.com/twitter/rustcommon", package="rustcommon-metrics-v2" }
macros = { path = "../macros" }
strum = "0.20.0"
strum_macros = "0.20.1"